# Generated by Django 4.2.5 on 2023-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_order_shippingprice_alter_order_taxprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="shippingPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
